apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis-cart-primary
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis-cart-primary
  type: ClusterIP
status:
  loadBalancer: {}
