apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: adservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - adservice.hipstershop-prod.demo1.keptn.live.demo.dynatrace.com
  - adservice
  http:
  - route:
    - destination:
        host: adservice.hipstershop-prod.svc.cluster.local
