apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cartservice-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice-primary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cartservice-primary
        app.kubernetes.io/instance: cartservice-canary
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cartservice-primary
        app.kubernetes.io/part-of: keptn-hipstershop-staging
        app.kubernetes.io/version: 9e830c2
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: redis-cart:6379
        - name: PORT
          value: "7070"
        - name: LISTEN_ADDR
          value: 0.0.0.0
        - name: DT_CUSTOM_PROP
          value: keptn_project=hipstershop keptn_service=cartservice keptn_stage=staging
            keptn_deployment=primary
        image: gcr.io/dynatrace-demoability/cartservice:9e830c2
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:7070
            - -rpc-timeout=3s
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
        name: server
        ports:
        - containerPort: 7070
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:7070
            - -rpc-timeout=3s
          initialDelaySeconds: 15
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 600m
            memory: 1Gi
          requests:
            cpu: 600m
            memory: 1Gi
      imagePullSecrets:
      - name: regcred
      terminationGracePeriodSeconds: 5
status: {}
