apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: checkoutservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - checkoutservice.hipstershop-staging.demo1.keptn.live.demo.dynatrace.com
  - checkoutservice
  http:
  - route:
    - destination:
        host: checkoutservice-canary.hipstershop-staging.svc.cluster.local
    - destination:
        host: checkoutservice-primary.hipstershop-staging.svc.cluster.local
      weight: 100
