apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: checkoutservice-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice-primary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: checkoutservice-primary
        app.kubernetes.io/instance: checkoutservice-canary
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: checkoutservice-primary
        app.kubernetes.io/part-of: keptn-hipstershop-staging
        app.kubernetes.io/version: 9e830c2
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=hipstershop keptn_service=checkoutservice keptn_stage=staging
            keptn_deployment=primary
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: PAYMENT_SERVICE_ADDR
          value: paymentservice:50051
        - name: EMAIL_SERVICE_ADDR
          value: emailservice:5000
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        image: gcr.io/dynatrace-demoability/checkoutservice:9e830c2
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:5050
        name: server
        ports:
        - containerPort: 5050
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:5050
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      imagePullSecrets:
      - name: regcred
status: {}
