apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: paymentservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - paymentservice.hipstershop-staging.demo1.keptn.live.demo.dynatrace.com
  - paymentservice
  http:
  - route:
    - destination:
        host: paymentservice-canary.hipstershop-staging.svc.cluster.local
      weight: 100
    - destination:
        host: paymentservice-primary.hipstershop-staging.svc.cluster.local
