apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: loadgenerator-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator-primary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadgenerator-primary
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=hipstershop keptn_service=loadgenerator keptn_stage=staging
            keptn_deployment=primary
        - name: FRONTEND_ADDR
          value: frontend:80
        - name: USERS
          value: "10"
        image: gcr.io/dynatrace-demoability/loadgenerator:9e830c2
        name: server
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
status: {}
